# Generated by Django 5.0.3 on 2024-05-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('parking_id', models.IntegerField(primary_key=True, serialize=False)),
                ('map', models.TextField()),
                ('address', models.TextField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('is_paid', models.BooleanField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('free_spaces', models.IntegerField()),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('is_parked', models.BooleanField(default=False)),
                ('current_parking_id', models.IntegerField(null=True)),
            ],
        ),
    ]
