# Generated by Django 5.0.3 on 2024-05-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_id_alter_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reserved_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='started_parking',
            field=models.DateTimeField(null=True),
        ),
    ]
